using System.Linq;
using System.Text;

namespace ActiveStateMachine.Generators
{
    /// <summary>
    /// Emits the modern asynchronous Active Object: a <c>System.Threading.Channels.Channel</c>
    /// mailbox drained by a worker <c>Task</c>, trigger methods returning <c>Task</c>, and
    /// <c>IAsyncDisposable</c>.
    /// </summary>
    internal static class AsyncEmitter
    {
        public static string Emit(ActiveObjectInfo info)
        {
            string machine = $"global::Stateless.StateMachine<{info.StateType}, {info.TriggerType}>";
            string messageBase = $"{info.ClassName}Message";
            string channelType = $"global::System.Threading.Channels.Channel<{messageBase}>";

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();

            bool hasNamespace = !string.IsNullOrEmpty(info.Namespace);
            string indent = hasNamespace ? "    " : string.Empty;
            if (hasNamespace)
            {
                sb.AppendLine($"namespace {info.Namespace}");
                sb.AppendLine("{");
            }

            sb.AppendLine($"{indent}partial class {info.ClassName}");
            sb.AppendLine($"{indent}{{");

            string b = indent + "    "; // member indent

            // --- 1. Fields ---
            sb.AppendLine($"{b}private readonly {machine} _machine;");
            sb.AppendLine($"{b}private readonly {channelType} _messageQueue;");
            sb.AppendLine($"{b}private readonly global::System.Threading.Tasks.Task _workerTask;");
            sb.AppendLine($"{b}private readonly global::System.Threading.CancellationTokenSource _cts;");

            // --- 2. Parameterized trigger fields ---
            foreach (TriggerMethodInfo method in info.Methods.Where(m => m.IsParameterized))
            {
                string generics = string.Join(", ", method.Parameters.Select(p => p.Type));
                sb.AppendLine(
                    $"{b}private readonly {machine}.TriggerWithParameters<{generics}> Trigger{method.Name};");
            }

            sb.AppendLine();

            // --- 3. Base message record ---
            sb.AppendLine($"{b}private abstract record {messageBase}");
            sb.AppendLine($"{b}{{");
            sb.AppendLine($"{b}    public global::System.Threading.Tasks.TaskCompletionSource Tcs {{ get; }} = new(global::System.Threading.Tasks.TaskCreationOptions.RunContinuationsAsynchronously);");
            sb.AppendLine($"{b}    public global::System.Threading.Tasks.Task Completion => Tcs.Task;");
            sb.AppendLine($"{b}    public abstract void Execute({info.ClassName} ao);");
            sb.AppendLine($"{b}}}");
            sb.AppendLine();

            // --- 4. Concrete message records ---
            foreach (TriggerMethodInfo method in info.Methods)
            {
                string ctorParams = string.Join(", ", method.Parameters.Select(p => $"{p.Type} {p.Name}"));
                sb.AppendLine($"{b}private sealed record {method.Name}Message({ctorParams}) : {messageBase}");
                sb.AppendLine($"{b}{{");
                sb.AppendLine($"{b}    public override void Execute({info.ClassName} ao) => {FireExpression(method)};");
                sb.AppendLine($"{b}}}");
                sb.AppendLine();
            }

            // --- 5. Constructor ---
            sb.AppendLine($"{b}public {info.ClassName}({info.StateType} initialState)");
            sb.AppendLine($"{b}{{");
            sb.AppendLine($"{b}    _machine = new {machine}(initialState);");
            foreach (TriggerMethodInfo method in info.Methods.Where(m => m.IsParameterized))
            {
                string generics = string.Join(", ", method.Parameters.Select(p => p.Type));
                sb.AppendLine(
                    $"{b}    Trigger{method.Name} = _machine.SetTriggerParameters<{generics}>({method.Trigger});");
            }

            sb.AppendLine($"{b}    ConfigureStateMachine();");
            sb.AppendLine();
            sb.AppendLine($"{b}    _messageQueue = global::System.Threading.Channels.Channel.CreateUnbounded<{messageBase}>(new global::System.Threading.Channels.UnboundedChannelOptions {{ SingleReader = true }});");
            sb.AppendLine($"{b}    _cts = new global::System.Threading.CancellationTokenSource();");
            sb.AppendLine($"{b}    _workerTask = global::System.Threading.Tasks.Task.Run(ProcessMailboxAsync);");
            sb.AppendLine($"{b}}}");
            sb.AppendLine();

            // Partial hook for the user's configuration.
            sb.AppendLine($"{b}partial void ConfigureStateMachine();");
            sb.AppendLine();

            // --- 6. Mailbox processor ---
            sb.AppendLine($"{b}private async global::System.Threading.Tasks.Task ProcessMailboxAsync()");
            sb.AppendLine($"{b}{{");
            sb.AppendLine($"{b}    try");
            sb.AppendLine($"{b}    {{");
            sb.AppendLine($"{b}        await foreach (var msg in _messageQueue.Reader.ReadAllAsync(_cts.Token).ConfigureAwait(false))");
            sb.AppendLine($"{b}        {{");
            sb.AppendLine($"{b}            try");
            sb.AppendLine($"{b}            {{");
            sb.AppendLine($"{b}                msg.Execute(this);");
            sb.AppendLine($"{b}                msg.Tcs.SetResult();");
            sb.AppendLine($"{b}            }}");
            sb.AppendLine($"{b}            catch (global::System.Exception ex)");
            sb.AppendLine($"{b}            {{");
            sb.AppendLine($"{b}                msg.Tcs.SetException(ex);");
            sb.AppendLine($"{b}            }}");
            sb.AppendLine($"{b}        }}");
            sb.AppendLine($"{b}    }}");
            sb.AppendLine($"{b}    catch (global::System.OperationCanceledException)");
            sb.AppendLine($"{b}    {{");
            sb.AppendLine($"{b}    }}");
            sb.AppendLine($"{b}}}");
            sb.AppendLine();

            // --- 7. Partial method implementations ---
            foreach (TriggerMethodInfo method in info.Methods)
            {
                string sigParams = string.Join(", ", method.Parameters.Select(p => $"{p.Type} {p.Name}"));
                string ctorArgs = string.Join(", ", method.Parameters.Select(p => p.Name));
                sb.AppendLine($"{b}{method.Accessibility} partial global::System.Threading.Tasks.Task {method.Name}({sigParams})");
                sb.AppendLine($"{b}{{");
                sb.AppendLine($"{b}    var __msg = new {method.Name}Message({ctorArgs});");
                sb.AppendLine($"{b}    return _messageQueue.Writer.TryWrite(__msg)");
                sb.AppendLine($"{b}        ? __msg.Completion");
                sb.AppendLine($"{b}        : global::System.Threading.Tasks.Task.FromException(new global::System.InvalidOperationException(\"Active Object message queue is closed.\"));");
                sb.AppendLine($"{b}}}");
                sb.AppendLine();
            }

            // --- 8. Async disposal ---
            sb.AppendLine($"{b}public async global::System.Threading.Tasks.ValueTask DisposeAsync()");
            sb.AppendLine($"{b}{{");
            sb.AppendLine($"{b}    _messageQueue.Writer.TryComplete();");
            sb.AppendLine($"{b}    try");
            sb.AppendLine($"{b}    {{");
            sb.AppendLine($"{b}        await _workerTask.ConfigureAwait(false);");
            sb.AppendLine($"{b}    }}");
            sb.AppendLine($"{b}    catch (global::System.OperationCanceledException)");
            sb.AppendLine($"{b}    {{");
            sb.AppendLine($"{b}    }}");
            sb.AppendLine($"{b}    _cts.Cancel();");
            sb.AppendLine($"{b}    _cts.Dispose();");
            sb.AppendLine($"{b}    global::System.GC.SuppressFinalize(this);");
            sb.AppendLine($"{b}}}");

            sb.AppendLine($"{indent}}}");
            if (hasNamespace)
            {
                sb.AppendLine("}");
            }

            return sb.ToString();
        }

        private static string FireExpression(TriggerMethodInfo method)
        {
            if (!method.IsParameterized)
            {
                return $"ao._machine.Fire({method.Trigger})";
            }

            string args = string.Join(", ", method.Parameters.Select(p => p.Name));
            return $"ao._machine.Fire(ao.Trigger{method.Name}, {args})";
        }
    }
}
