using System.Linq;
using System.Text;

namespace ActiveStateMachine.Generators
{
    /// <summary>
    /// Emits the modern asynchronous Active Object: a <c>System.Threading.Channels.Channel</c>
    /// mailbox drained by a worker <c>Task</c>, trigger methods returning <c>Task</c>, and
    /// <c>IAsyncDisposable</c>.
    /// </summary>
    internal static class AsyncEmitter
    {
        public static string Emit(ActiveObjectInfo info)
        {
            string machine = $"global::Stateless.StateMachine<{info.StateType}, {info.TriggerType}>";
            string messageBase = $"{info.ClassName}Message";
            string channelType = $"global::System.Threading.Channels.Channel<{messageBase}>";
            string defaultName = Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(
                info.Name ?? info.ClassName, quote: true);

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();

            bool hasNamespace = !string.IsNullOrEmpty(info.Namespace);
            string indent = hasNamespace ? "    " : string.Empty;
            if (hasNamespace)
            {
                sb.AppendLine($"namespace {info.Namespace}");
                sb.AppendLine("{");
            }

            sb.AppendLine($"{indent}partial class {info.ClassName}{info.TypeParameters}{info.TypeParameterConstraints}");
            sb.AppendLine($"{indent}{{");

            string b = indent + "    "; // member indent
            string aoType = info.ClassNameWithTypeParameters; // the Active Object's own (possibly generic) type

            // --- 1. Fields ---
            sb.AppendLine($"{b}private readonly {machine} _machine;");
            sb.AppendLine($"{b}private readonly {channelType} _messageQueue;");
            sb.AppendLine($"{b}private readonly global::System.Threading.Tasks.Task _workerTask;");
            sb.AppendLine($"{b}private readonly global::System.Threading.CancellationTokenSource _cts;");
            sb.AppendLine($"{b}private readonly string _name;");
            sb.AppendLine($"{b}private bool _disposed;");
            sb.AppendLine();
            sb.AppendLine($"{b}/// <summary>The name of the Active Object whose worker is currently running. Set on the worker");
            sb.AppendLine($"{b}/// task and flows with the async execution context, so any code executed by this Active Object");
            sb.AppendLine($"{b}/// (including Stateless entry/exit actions) can read it.</summary>");
            sb.AppendLine($"{b}public static readonly global::System.Threading.AsyncLocal<string?> CurrentActiveObjectName = new global::System.Threading.AsyncLocal<string?>();");
            sb.AppendLine();
            sb.AppendLine($"{b}/// <summary>The name of this Active Object instance.</summary>");
            sb.AppendLine($"{b}public string Name => _name;");

            // --- 2. Parameterized trigger fields ---
            foreach (TriggerMethodInfo method in info.Methods.Where(m => m.IsParameterized))
            {
                string generics = string.Join(", ", method.Parameters.Select(p => p.Type));
                sb.AppendLine(
                    $"{b}private readonly {machine}.TriggerWithParameters<{generics}> Trigger{method.Name};");
            }

            sb.AppendLine();

            // --- 3. Base message record ---
            sb.AppendLine($"{b}private abstract record {messageBase}");
            sb.AppendLine($"{b}{{");
            sb.AppendLine($"{b}    public global::System.Threading.Tasks.TaskCompletionSource Tcs {{ get; }} = new(global::System.Threading.Tasks.TaskCreationOptions.RunContinuationsAsynchronously);");
            sb.AppendLine($"{b}    public global::System.Threading.Tasks.Task Completion => Tcs.Task;");
            sb.AppendLine($"{b}    public abstract void Execute({aoType} ao);");
            sb.AppendLine($"{b}}}");
            sb.AppendLine();

            // --- 4. Concrete message records ---
            foreach (TriggerMethodInfo method in info.Methods)
            {
                string ctorParams = string.Join(", ", method.Parameters.Select(p => $"{p.Type} {p.Name}"));
                sb.AppendLine($"{b}private sealed record {method.Name}Message({ctorParams}) : {messageBase}");
                sb.AppendLine($"{b}{{");
                sb.AppendLine($"{b}    public override void Execute({aoType} ao) => {FireExpression(method)};");
                sb.AppendLine($"{b}}}");
                sb.AppendLine();
            }

            // --- 5. Constructor ---
            sb.AppendLine($"{b}public {info.ClassName}({info.StateType} initialState, string? name = null)");
            sb.AppendLine($"{b}{{");
            sb.AppendLine($"{b}    _name = name ?? {defaultName};");
            sb.AppendLine($"{b}    _machine = new {machine}(initialState);");
            foreach (TriggerMethodInfo method in info.Methods.Where(m => m.IsParameterized))
            {
                string generics = string.Join(", ", method.Parameters.Select(p => p.Type));
                sb.AppendLine(
                    $"{b}    Trigger{method.Name} = _machine.SetTriggerParameters<{generics}>({method.Trigger});");
            }

            sb.AppendLine($"{b}    ConfigureStateMachine();");
            sb.AppendLine();
            sb.AppendLine($"{b}    _messageQueue = global::System.Threading.Channels.Channel.CreateUnbounded<{messageBase}>(new global::System.Threading.Channels.UnboundedChannelOptions {{ SingleReader = true }});");
            sb.AppendLine($"{b}    _cts = new global::System.Threading.CancellationTokenSource();");
            sb.AppendLine($"{b}    _workerTask = global::System.Threading.Tasks.Task.Run(ProcessMailboxAsync);");
            sb.AppendLine($"{b}}}");
            sb.AppendLine();

            // Partial hook for the user's configuration.
            sb.AppendLine($"{b}partial void ConfigureStateMachine();");
            sb.AppendLine();

            // Partial hook invoked at the start of DisposeAsync(), before the mailbox is completed and
            // the worker is awaited. Lets the class release resources it owns (unsubscribe events, stop
            // auxiliary threads). An unimplemented partial is elided, so it is entirely optional.
            sb.AppendLine($"{b}partial void OnDisposing();");
            sb.AppendLine();

            // --- 6. Mailbox processor ---
            sb.AppendLine($"{b}private async global::System.Threading.Tasks.Task ProcessMailboxAsync()");
            sb.AppendLine($"{b}{{");
            sb.AppendLine($"{b}    // Flows to every message processed on this worker (and any tasks it awaits).");
            sb.AppendLine($"{b}    CurrentActiveObjectName.Value = _name;");
            sb.AppendLine($"{b}    try");
            sb.AppendLine($"{b}    {{");
            sb.AppendLine($"{b}        await foreach (var msg in _messageQueue.Reader.ReadAllAsync(_cts.Token).ConfigureAwait(false))");
            sb.AppendLine($"{b}        {{");
            sb.AppendLine($"{b}            try");
            sb.AppendLine($"{b}            {{");
            sb.AppendLine($"{b}                msg.Execute(this);");
            sb.AppendLine($"{b}                msg.Tcs.SetResult();");
            sb.AppendLine($"{b}            }}");
            sb.AppendLine($"{b}            catch (global::System.Exception ex)");
            sb.AppendLine($"{b}            {{");
            sb.AppendLine($"{b}                msg.Tcs.SetException(ex);");
            sb.AppendLine($"{b}            }}");
            sb.AppendLine($"{b}        }}");
            sb.AppendLine($"{b}    }}");
            sb.AppendLine($"{b}    catch (global::System.OperationCanceledException)");
            sb.AppendLine($"{b}    {{");
            sb.AppendLine($"{b}    }}");
            sb.AppendLine($"{b}}}");
            sb.AppendLine();

            // --- 7. Partial method implementations ---
            // Wait == true  -> return the task that completes when the worker has processed the message
            //                  (surfacing any processing exception to the awaiter).
            // Wait == false -> enqueue and return an already-completed task; the caller neither awaits
            //                  processing nor observes its exceptions. Use this for triggers fired from
            //                  another Active Object's worker to avoid cross-object deadlocks.
            foreach (TriggerMethodInfo method in info.Methods)
            {
                string sigParams = string.Join(", ", method.Parameters.Select(p => $"{p.Type} {p.Name}"));
                string ctorArgs = string.Join(", ", method.Parameters.Select(p => p.Name));
                sb.AppendLine($"{b}{method.Modifiers} partial global::System.Threading.Tasks.Task {method.Name}({sigParams})");
                sb.AppendLine($"{b}{{");
                sb.AppendLine($"{b}    var __msg = new {method.Name}Message({ctorArgs});");
                if (method.Wait)
                {
                    sb.AppendLine($"{b}    return _messageQueue.Writer.TryWrite(__msg)");
                    sb.AppendLine($"{b}        ? __msg.Completion");
                    sb.AppendLine($"{b}        : global::System.Threading.Tasks.Task.FromException(new global::System.InvalidOperationException(\"Active Object message queue is closed.\"));");
                }
                else
                {
                    sb.AppendLine($"{b}    if (!_messageQueue.Writer.TryWrite(__msg))");
                    sb.AppendLine($"{b}    {{");
                    sb.AppendLine($"{b}        return global::System.Threading.Tasks.Task.FromException(new global::System.InvalidOperationException(\"Active Object message queue is closed.\"));");
                    sb.AppendLine($"{b}    }}");
                    sb.AppendLine();
                    sb.AppendLine($"{b}    // Observe (and discard) any processing fault so it never surfaces as an UnobservedTaskException.");
                    sb.AppendLine($"{b}    __msg.Completion.ContinueWith(");
                    sb.AppendLine($"{b}        static t => {{ _ = t.Exception; }},");
                    sb.AppendLine($"{b}        global::System.Threading.Tasks.TaskContinuationOptions.OnlyOnFaulted |");
                    sb.AppendLine($"{b}        global::System.Threading.Tasks.TaskContinuationOptions.ExecuteSynchronously);");
                    sb.AppendLine($"{b}    return global::System.Threading.Tasks.Task.CompletedTask;");
                }

                sb.AppendLine($"{b}}}");
                sb.AppendLine();
            }

            // --- 8. Async disposal ---
            // 'override' when a base type already exposes an overridable DisposeAsync (so disposal
            // dispatches through a base reference); otherwise 'virtual'.
            string disposeModifier = info.BaseHasOverridableDisposeAsync ? "override" : "virtual";
            sb.AppendLine($"{b}public {disposeModifier} async global::System.Threading.Tasks.ValueTask DisposeAsync()");
            sb.AppendLine($"{b}{{");
            sb.AppendLine($"{b}    if (_disposed) {{ return; }}");
            sb.AppendLine($"{b}    _disposed = true;");
            sb.AppendLine($"{b}    OnDisposing();");
            sb.AppendLine($"{b}    _messageQueue.Writer.TryComplete();");
            sb.AppendLine($"{b}    try");
            sb.AppendLine($"{b}    {{");
            sb.AppendLine($"{b}        await _workerTask.ConfigureAwait(false);");
            sb.AppendLine($"{b}    }}");
            sb.AppendLine($"{b}    catch (global::System.OperationCanceledException)");
            sb.AppendLine($"{b}    {{");
            sb.AppendLine($"{b}    }}");
            sb.AppendLine($"{b}    _cts.Cancel();");
            sb.AppendLine($"{b}    _cts.Dispose();");
            sb.AppendLine($"{b}    global::System.GC.SuppressFinalize(this);");
            sb.AppendLine($"{b}}}");

            sb.AppendLine($"{indent}}}");
            if (hasNamespace)
            {
                sb.AppendLine("}");
            }

            return sb.ToString();
        }

        private static string FireExpression(TriggerMethodInfo method)
        {
            if (!method.IsParameterized)
            {
                return $"ao._machine.Fire({method.Trigger})";
            }

            string args = string.Join(", ", method.Parameters.Select(p => p.Name));
            return $"ao._machine.Fire(ao.Trigger{method.Name}, {args})";
        }
    }
}
