namespace ActiveStateMachine.Generators
{
    /// <summary>
    /// The C# source for the marker attributes. The generator injects this into every consuming
    /// compilation via <c>RegisterPostInitializationOutput</c>, so consumers do not need to
    /// reference a separate attributes assembly — the package is analyzer-only.
    /// </summary>
    /// <remarks>
    /// The attributes are emitted as <c>internal</c> so each consuming assembly gets its own copy
    /// with no cross-assembly collisions. Their metadata names still match the strings the generator
    /// looks for, so discovery via <c>ForAttributeWithMetadataName</c> works against the
    /// post-initialization source exactly as it would against a referenced assembly.
    /// <para>
    /// <c>[ActiveObjectAsync]</c> selects the modern async/<c>Channel</c>/<c>Task</c> implementation;
    /// <c>[ActiveObjectSync]</c> selects the classic blocking <c>Thread</c>/<c>BlockingCollection</c>
    /// implementation. <c>[StateTrigger]</c> is shared by both.
    /// </para>
    /// </remarks>
    internal static class EmbeddedAttributes
    {
        public const string HintName = "ActiveStateMachine.Attributes.g.cs";

        public const string Source =
"""
// <auto-generated/>
#nullable enable
#pragma warning disable

namespace ActiveStateMachine.Attributes
{
    /// <summary>
    /// Marks a partial class as an <b>asynchronous</b> Active Object backed by a Stateless state
    /// machine and a <c>System.Threading.Channels.Channel</c> mailbox. The source generator emits
    /// the state machine, mailbox, worker <c>Task</c>, message plumbing and <c>IAsyncDisposable</c>
    /// for the class. Trigger methods return <c>Task</c>.
    /// </summary>
    /// <remarks>
    /// The decorated class MUST be declared <c>partial</c> and SHOULD declare a
    /// <c>partial void ConfigureStateMachine();</c> method that configures the underlying
    /// <c>Stateless.StateMachine</c>.
    /// </remarks>
    [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
    [global::System.CodeDom.Compiler.GeneratedCode("ActiveStateMachine.Generators", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCode]
    internal sealed class ActiveObjectAsyncAttribute : global::System.Attribute
    {
        /// <summary>Creates the attribute.</summary>
        /// <param name="stateType">The enum type used for states.</param>
        /// <param name="triggerType">The enum type used for triggers.</param>
        public ActiveObjectAsyncAttribute(global::System.Type stateType, global::System.Type triggerType)
        {
            StateType = stateType;
            TriggerType = triggerType;
        }

        /// <summary>The enum type used for states.</summary>
        public global::System.Type StateType { get; }

        /// <summary>The enum type used for triggers.</summary>
        public global::System.Type TriggerType { get; }

        /// <summary>
        /// Optional name for this Active Object. Used as the value of the generated
        /// <c>CurrentActiveObjectName</c> <c>AsyncLocal</c> while the worker runs. If left null it
        /// defaults to the class name, and it can be overridden per-instance via the constructor's
        /// <c>name</c> parameter.
        /// </summary>
        public string? Name { get; set; }
    }

    /// <summary>
    /// Marks a partial class as a <b>synchronous</b> Active Object backed by a Stateless state
    /// machine and a <c>System.Collections.Concurrent.BlockingCollection</c> processed by a
    /// dedicated background <c>System.Threading.Thread</c>. The source generator emits the state
    /// machine, the queue, the worker thread, message plumbing and <c>IDisposable</c> for the class.
    /// Trigger methods return <c>void</c> and block the caller until the message has been processed.
    /// </summary>
    /// <remarks>
    /// The decorated class MUST be declared <c>partial</c> and SHOULD declare a
    /// <c>partial void ConfigureStateMachine();</c> method that configures the underlying
    /// <c>Stateless.StateMachine</c>.
    /// </remarks>
    [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
    [global::System.CodeDom.Compiler.GeneratedCode("ActiveStateMachine.Generators", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCode]
    internal sealed class ActiveObjectSyncAttribute : global::System.Attribute
    {
        /// <summary>Creates the attribute.</summary>
        /// <param name="stateType">The enum type used for states.</param>
        /// <param name="triggerType">The enum type used for triggers.</param>
        public ActiveObjectSyncAttribute(global::System.Type stateType, global::System.Type triggerType)
        {
            StateType = stateType;
            TriggerType = triggerType;
        }

        /// <summary>The enum type used for states.</summary>
        public global::System.Type StateType { get; }

        /// <summary>The enum type used for triggers.</summary>
        public global::System.Type TriggerType { get; }

        /// <summary>
        /// Optional name for this Active Object. Used as the name of the generated background worker
        /// <c>Thread</c> (visible in the debugger). If left null it defaults to the class name, and it
        /// can be overridden per-instance via the constructor's <c>name</c> parameter.
        /// </summary>
        public string? Name { get; set; }
    }

    /// <summary>
    /// Marks a partial method as the public entry point for a state machine trigger. The source
    /// generator implements the method body so that calling it enqueues a message onto the Active
    /// Object's queue and fires the associated trigger on the worker.
    /// </summary>
    /// <remarks>
    /// The decorated method MUST be <c>partial</c>. For an <c>[ActiveObjectAsync]</c> class it must
    /// return <c>Task</c>; for an <c>[ActiveObjectSync]</c> class it must return <c>void</c>. A
    /// method with zero parameters maps to a plain trigger; a method with 1-3 parameters maps to a
    /// <c>TriggerWithParameters</c>.
    /// </remarks>
    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
    [global::System.CodeDom.Compiler.GeneratedCode("ActiveStateMachine.Generators", "1.2.0")]
    [global::System.Diagnostics.DebuggerNonUserCode]
    internal sealed class StateTriggerAttribute : global::System.Attribute
    {
        /// <summary>Creates the attribute.</summary>
        /// <param name="trigger">
        /// The trigger enum value, written as it appears in source, e.g. "PhoneTrigger.CallDialed".
        /// </param>
        public StateTriggerAttribute(string trigger)
        {
            Trigger = trigger;
        }

        /// <summary>The trigger enum value expressed as source text.</summary>
        public string Trigger { get; }
    }
}
""";
    }
}
