using System.Linq;
using System.Text;

namespace ActiveStateMachine.Generators
{
    /// <summary>
    /// Emits the classic synchronous Active Object: a
    /// <c>System.Collections.Concurrent.BlockingCollection</c> drained by a dedicated background
    /// <c>System.Threading.Thread</c>, trigger methods that return <c>void</c> and block the caller
    /// until their message has been processed (using a <c>TaskCompletionSource</c> purely as the
    /// wait/exception-marshalling primitive), and <c>IDisposable</c>. No <c>async</c>/<c>await</c>,
    /// no <c>Task</c>-returning API, and no <c>Channel</c>.
    /// </summary>
    internal static class SyncEmitter
    {
        public static string Emit(ActiveObjectInfo info)
        {
            string machine = $"global::Stateless.StateMachine<{info.StateType}, {info.TriggerType}>";
            string messageBase = $"{info.ClassName}Message";
            string queueType = $"global::System.Collections.Concurrent.BlockingCollection<{messageBase}>";
            string defaultName = Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(
                info.Name ?? info.ClassName, quote: true);

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();

            bool hasNamespace = !string.IsNullOrEmpty(info.Namespace);
            string indent = hasNamespace ? "    " : string.Empty;
            if (hasNamespace)
            {
                sb.AppendLine($"namespace {info.Namespace}");
                sb.AppendLine("{");
            }

            sb.AppendLine($"{indent}partial class {info.ClassName}");
            sb.AppendLine($"{indent}{{");

            string b = indent + "    "; // member indent

            // --- 1. Fields ---
            sb.AppendLine($"{b}private readonly {machine} _machine;");
            sb.AppendLine($"{b}private readonly {queueType} _messageQueue;");
            sb.AppendLine($"{b}private readonly global::System.Threading.Thread _workerThread;");
            sb.AppendLine($"{b}private readonly string _name;");
            sb.AppendLine();
            sb.AppendLine($"{b}/// <summary>The name of this Active Object instance. It is also the name of the background");
            sb.AppendLine($"{b}/// worker <see cref=\"global::System.Threading.Thread\"/>, so it is visible in the debugger.</summary>");
            sb.AppendLine($"{b}public string Name => _name;");

            // --- 2. Parameterized trigger fields ---
            foreach (TriggerMethodInfo method in info.Methods.Where(m => m.IsParameterized))
            {
                string generics = string.Join(", ", method.Parameters.Select(p => p.Type));
                sb.AppendLine(
                    $"{b}private readonly {machine}.TriggerWithParameters<{generics}> Trigger{method.Name};");
            }

            sb.AppendLine();

            // --- 3. Base message class ---
            sb.AppendLine($"{b}private abstract class {messageBase}");
            sb.AppendLine($"{b}{{");
            sb.AppendLine($"{b}    public global::System.Threading.Tasks.TaskCompletionSource<bool> Tcs {{ get; }} = new global::System.Threading.Tasks.TaskCompletionSource<bool>(global::System.Threading.Tasks.TaskCreationOptions.RunContinuationsAsynchronously);");
            sb.AppendLine($"{b}    public abstract void Execute({info.ClassName} ao);");
            sb.AppendLine($"{b}}}");
            sb.AppendLine();

            // --- 4. Concrete message classes ---
            foreach (TriggerMethodInfo method in info.Methods)
            {
                sb.AppendLine($"{b}private sealed class {method.Name}Message : {messageBase}");
                sb.AppendLine($"{b}{{");
                foreach (ParameterInfo p in method.Parameters)
                {
                    sb.AppendLine($"{b}    private readonly {p.Type} {p.Name};");
                }

                if (method.IsParameterized)
                {
                    string ctorParams = string.Join(", ", method.Parameters.Select(p => $"{p.Type} {p.Name}"));
                    sb.AppendLine($"{b}    public {method.Name}Message({ctorParams})");
                    sb.AppendLine($"{b}    {{");
                    foreach (ParameterInfo p in method.Parameters)
                    {
                        sb.AppendLine($"{b}        this.{p.Name} = {p.Name};");
                    }

                    sb.AppendLine($"{b}    }}");
                }

                sb.AppendLine($"{b}    public override void Execute({info.ClassName} ao) => {FireExpression(method)};");
                sb.AppendLine($"{b}}}");
                sb.AppendLine();
            }

            // --- 5. Constructor ---
            sb.AppendLine($"{b}public {info.ClassName}({info.StateType} initialState, string? name = null)");
            sb.AppendLine($"{b}{{");
            sb.AppendLine($"{b}    _name = name ?? {defaultName};");
            sb.AppendLine($"{b}    _machine = new {machine}(initialState);");
            foreach (TriggerMethodInfo method in info.Methods.Where(m => m.IsParameterized))
            {
                string generics = string.Join(", ", method.Parameters.Select(p => p.Type));
                sb.AppendLine(
                    $"{b}    Trigger{method.Name} = _machine.SetTriggerParameters<{generics}>({method.Trigger});");
            }

            sb.AppendLine($"{b}    ConfigureStateMachine();");
            sb.AppendLine();
            sb.AppendLine($"{b}    _messageQueue = new {queueType}();");
            sb.AppendLine($"{b}    _workerThread = new global::System.Threading.Thread(ProcessMessages)");
            sb.AppendLine($"{b}    {{");
            sb.AppendLine($"{b}        IsBackground = true,");
            sb.AppendLine($"{b}        Name = _name,");
            sb.AppendLine($"{b}    }};");
            sb.AppendLine($"{b}    _workerThread.Start();");
            sb.AppendLine($"{b}}}");
            sb.AppendLine();

            // Partial hook for the user's configuration.
            sb.AppendLine($"{b}partial void ConfigureStateMachine();");
            sb.AppendLine();

            // Partial hook invoked at the start of Dispose(), before the queue is completed and the
            // worker is joined. Lets the class release resources it owns (unsubscribe events, stop
            // auxiliary threads). An unimplemented partial is elided, so it is entirely optional.
            sb.AppendLine($"{b}partial void OnDisposing();");
            sb.AppendLine();

            // --- 6. Worker loop (dedicated thread) ---
            sb.AppendLine($"{b}private void ProcessMessages()");
            sb.AppendLine($"{b}{{");
            sb.AppendLine($"{b}    foreach (var msg in _messageQueue.GetConsumingEnumerable())");
            sb.AppendLine($"{b}    {{");
            sb.AppendLine($"{b}        try");
            sb.AppendLine($"{b}        {{");
            sb.AppendLine($"{b}            msg.Execute(this);");
            sb.AppendLine($"{b}            msg.Tcs.SetResult(true);");
            sb.AppendLine($"{b}        }}");
            sb.AppendLine($"{b}        catch (global::System.Exception ex)");
            sb.AppendLine($"{b}        {{");
            sb.AppendLine($"{b}            msg.Tcs.SetException(ex);");
            sb.AppendLine($"{b}        }}");
            sb.AppendLine($"{b}    }}");
            sb.AppendLine($"{b}}}");
            sb.AppendLine();

            // --- 7. Trigger method implementations (void) ---
            // Wait == true  -> block the caller until the worker has processed the message.
            // Wait == false -> only enqueue and return immediately (fire-and-forget); the caller
            //                  neither blocks nor observes processing exceptions. Use this for triggers
            //                  fired from another Active Object's worker thread to avoid deadlocks.
            foreach (TriggerMethodInfo method in info.Methods)
            {
                string sigParams = string.Join(", ", method.Parameters.Select(p => $"{p.Type} {p.Name}"));
                string ctorArgs = string.Join(", ", method.Parameters.Select(p => p.Name));
                string sendMethod = method.Wait ? "SendAndWait" : "Send";
                sb.AppendLine($"{b}{method.Accessibility} partial void {method.Name}({sigParams})");
                sb.AppendLine($"{b}{{");
                sb.AppendLine($"{b}    {sendMethod}(new {method.Name}Message({ctorArgs}));");
                sb.AppendLine($"{b}}}");
                sb.AppendLine();
            }

            // --- 8. Send helpers ---
            sb.AppendLine($"{b}private void Enqueue({messageBase} message)");
            sb.AppendLine($"{b}{{");
            sb.AppendLine($"{b}    try");
            sb.AppendLine($"{b}    {{");
            sb.AppendLine($"{b}        _messageQueue.Add(message);");
            sb.AppendLine($"{b}    }}");
            sb.AppendLine($"{b}    catch (global::System.InvalidOperationException)");
            sb.AppendLine($"{b}    {{");
            sb.AppendLine($"{b}        throw new global::System.InvalidOperationException(\"Active Object message queue is closed.\");");
            sb.AppendLine($"{b}    }}");
            sb.AppendLine($"{b}}}");
            sb.AppendLine();
            sb.AppendLine($"{b}// Enqueue and block the calling thread until the worker has processed the message,");
            sb.AppendLine($"{b}// rethrowing any exception it produced (no wrapping AggregateException).");
            sb.AppendLine($"{b}private void SendAndWait({messageBase} message)");
            sb.AppendLine($"{b}{{");
            sb.AppendLine($"{b}    Enqueue(message);");
            sb.AppendLine($"{b}    message.Tcs.Task.GetAwaiter().GetResult();");
            sb.AppendLine($"{b}}}");
            sb.AppendLine();
            sb.AppendLine($"{b}// Enqueue and return immediately. The processing result/exception is observed (but");
            sb.AppendLine($"{b}// discarded) so a fault never surfaces as an UnobservedTaskException.");
            sb.AppendLine($"{b}private void Send({messageBase} message)");
            sb.AppendLine($"{b}{{");
            sb.AppendLine($"{b}    Enqueue(message);");
            sb.AppendLine($"{b}    message.Tcs.Task.ContinueWith(");
            sb.AppendLine($"{b}        static t => {{ _ = t.Exception; }},");
            sb.AppendLine($"{b}        global::System.Threading.Tasks.TaskContinuationOptions.OnlyOnFaulted |");
            sb.AppendLine($"{b}        global::System.Threading.Tasks.TaskContinuationOptions.ExecuteSynchronously);");
            sb.AppendLine($"{b}}}");
            sb.AppendLine();

            // --- 9. Disposal ---
            sb.AppendLine($"{b}public void Dispose()");
            sb.AppendLine($"{b}{{");
            sb.AppendLine($"{b}    OnDisposing();");
            sb.AppendLine($"{b}    _messageQueue.CompleteAdding();");
            sb.AppendLine($"{b}    _workerThread.Join();");
            sb.AppendLine($"{b}    _messageQueue.Dispose();");
            sb.AppendLine($"{b}    global::System.GC.SuppressFinalize(this);");
            sb.AppendLine($"{b}}}");

            sb.AppendLine($"{indent}}}");
            if (hasNamespace)
            {
                sb.AppendLine("}");
            }

            return sb.ToString();
        }

        private static string FireExpression(TriggerMethodInfo method)
        {
            if (!method.IsParameterized)
            {
                return $"ao._machine.Fire({method.Trigger})";
            }

            string args = string.Join(", ", method.Parameters.Select(p => p.Name));
            return $"ao._machine.Fire(ao.Trigger{method.Name}, {args})";
        }
    }
}
